### ISSUE TITLE
release 0.0.2 undefined references with WSL2

### ISSUE THREAD

**Issue by WillTheCodeWork** [tim-tm/ped#4]
# release 0.0.2 undefined references
I am on WSL2, when I run it the program says I do not have references to the following (I installed ncurses):
stdscr
wmove
wrefresh
noecho
raw
newwin
keypad
werase
is_term_resized
mvwprintw
wrefresh
delwin
endwin
wmove

it also seems to be a linker error, also I think this excerpt may be helpful:
/usr/bin/ld: src/ped-main.o: warning: relocation against `stdscr' in read-only section `.text.startup'
/usr/bin/ld: src/ped-main.o: in function `main':

after this it proceded to list all of the undefined references

**Comment by WillTheCodeWork** [comment]
# some things I forgot to mention
I am running Ubuntu, I also used this guide to download ncurses: [https://www.cyberciti.biz/faq/linux-install-ncurses-library-headers-on-debian-ubuntu-centos-fedora/](https://www.cyberciti.biz/faq/linux-install-ncurses-library-headers-on-debian-ubuntu-centos-fedora/)

**Comment by tim-tm** [comment]
Hi, after testing a bit around with WSL2 and Ubuntu, I might have found the reason why this error occurs.

I've been trying to compile with gcc, but autoconf inserted the linker flag before providing the source files. I assume that the Ubuntu packaged gcc (or every version of gcc11) does not like that behavior.

Therefore I just installed clang and the compilation worked fine. I didn't notice this issue because the arch packaged gcc (gcc13) seems to not be as strict with the order of arguments.

I would still not advise you to use ped as of right now, it is extremely unstable. Anyways, tell me if using clang worked for you so I can close this issue.

**Comment by WillTheCodeWork** [comment]
sorry for the inconveniouns, I am just going to leave this alone
